name: fotohora_tracker
description: A new Flutter project for tracking field technicians.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
  firebase_auth: ^4.16.0

  # Location
  flutter_background_geolocation: ^4.15.2

  # Camera & Image
  camera: ^0.10.5+5
  image: ^4.1.3

  # Local Storage & Connectivity
  path_provider: ^2.1.1
  connectivity_plus: ^5.0.2

  # Sharing
  share_plus: ^7.2.1

  # Utility
  intl: ^0.18.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
